# Generated by Django 4.1.1 on 2023-01-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('tractor_brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tractor_implements', models.CharField(max_length=50)),
            ],
        ),
    ]
