# Generated by Django 4.1.1 on 2023-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='tractor_implements',
            field=models.CharField(choices=[('Grams', 'Grams'), ('Ounces', 'Ounces'), ('Pieces', 'Pieces')], max_length=50),
        ),
    ]
