# Generated by Django 4.1.1 on 2023-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_farm_tractor_implements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
