# Generated by Django 4.1.1 on 2023-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_farm_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='tractor_implements',
            field=models.CharField(choices=[('Harrow', 'Harrow'), ('Cultivator', 'Cultivator'), ('Rotavator', 'Rotavator'), ('Plough', 'Plough'), ('Paddy Thrasher', 'Paddy Thrasher'), ('Dumping Trailer', 'Dumping Trailer'), ('4 wheel Trailer', '4 wheel Trailer')], max_length=50),
        ),
    ]
